yatube/posts/urls.py
from django.urls import path
from . import views
app_name = 'posts'

urlpatterns = [
    # Главная страница
    path('', views.index, name='main'),
    path('group/<slug:slug>/', views.group_posts, name='group')
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
]

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self) -> str:
        return self.title


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        related_name='posts',
        blank=True,
        null=True
    )

    class Meta():
        ordering = ['-pub_date']

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Group


COUNT_POSTS = 10


def index(request):
    # в переменную posts будет сохранена выборка из 10 объектов модели Post,
    # отсортированных по полю pub_date по убыванию
    # (от больших значений к меньшим)
    posts = Post.objects.all()[:COUNT_POSTS]
    # В словаре context отправляем информацию в шаблон
    context = {
        'posts': posts,
        'title': "Последние обновления на сайте"
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()[:COUNT_POSTS]
    context = {
        'group': group,
        'posts': posts,
        'title': group.title,
        'main_header': "Лев Толстой – зеркало русской революции."
    }
    return render(request, 'posts/group_list.html', context)

yatube/templates/base.html
<!DOCTYPE html> 
<html lang="ru">          
  <head>
    <meta charset="utf-8"> <!-- Кодировка сайта -->
    {% load static %}
    <!-- Сайт готов работать с мобильными устройствами -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Загружаем фав-иконки -->
    <link rel="icon" href="img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <!-- Подключен файл со стандартными стилями бустрап -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>
      {% block title %}
        Контент не подвезли :(
      {% endblock %}
    </title>
  </head>
  <body>       
    <header>
      {% include 'includes/header.html' %}
    </header>
    <main>
      {% block content %}
        Контент не подвезли :(
      {% endblock %}
    </main>
    <footer>
      {% include 'includes/footer.html' %} 
    </footer>
  </body>
</html> 

yatube/templates/includes/footer.html
<div class="footer-copyright text-center py-3">© 2020 Copyright 
    <p><span style="color:red">Ya</span>tube</p> 
</div>  

yatube/templates/includes/header.html
{% load static %}
<!-- Использованы классы бустрапа для создания типовой навигации с логотипом -->
<!-- В дальнейшем тут будет создано полноценное меню -->    
<nav class="navbar navbar-light" style="background-color: lightskyblue">
<div class="container">
    <a class="navbar-brand" href="{% url 'posts:main'%}">
    <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
    <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
    <span style="color:red">Ya</span>tube
    </a>
</div>
</nav> 

yatube/templates/posts/group_list.html
<!-- templates/ice_cream/index.html --> 
{% extends 'base.html' %}
{%block title%}
{{title}}
{%endblock title%}
{% block content %}
<!-- класс py-5 создает отступы сверху и снизу блока -->
<div class="container py-5">
  <h1>{{main_header}}</h1>
  <p>
    {{group}}
  </p>
  {% for post in posts%}
  <article>
    <ul>
      <li>
        Автор: {{ post.author.get_full_name }}
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>      
    <p>
      {{ post.text }}
    </p>         
  </article>
  <!-- под последним постом нет линии -->
  {% if not forloop.last %}<hr>{% endif %}
  {% endfor%}
</div> 
{% endblock %} 

yatube/templates/posts/index.html
<!-- templates/ice_cream/index.html --> 
{% extends 'base.html' %}
{%block title%}
{{title}}
{%endblock title%}
{% block content %}
<div class="container py-5">
<h1>{{title}}</h1>
{% for post in posts %}
  <ul>
    <li>
      Автор: {{ post.author.get_full_name }}
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
  </ul>
  <p>{{ post.text }}</p>
  {%if post.group%}
  <a href="{%url 'posts:group' post.group.slug %}">все записи группы</a>
  {%endif%}
  {% if not forloop.last %}<hr>{% endif %}
{% endfor %} 
{% endblock %}
</div>